project:
  type: website
  output-dir: docs

website:
  title: "Janelia Data Standards"
  navbar:
    tools:
      - icon: github
        href: https://github.com/JaneliaSciComp/JaneliaDataStandards
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



