project:
  type: website

execute:
  freeze: auto

website:
  title: "Janelia Data Standards"
  navbar:
    tools:
      - icon: github
        href: https://github.com/JaneliaSciComp/JaneliaDataStandards
    left:
      - text: About
        href: about.qmd
      - text: Posts
        href: posts.qmd
      - text: File Formats
        menu:
          - text: Overview
            href: file_formats.qmd
          - text: Metadata features
            href: metadata.qmd
      - text: Definitions
        href: definitions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

