project:
  type: website

execute:
  freeze: auto

website:
  title: "Janelia Data Standards"
  navbar:
    tools:
      - icon: github
        href: https://github.com/JaneliaSciComp/JaneliaDataStandards
    left:
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
      - href: file_formats.qmd
        text: File Formats
      - href: definitions.qmd
        text: Definitions

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

