# Definitions
Please note that this is a living document. Definitions are preliminary and subject to change.

- Basic definitions
    - [array](#array)
    - [image](#image)
    - [pixel](#pixel)
    - [sample](#sample)
    - [voxel](#voxel)
- Other definitions
    - [axis](#axis)
    - [bit-depth](#bit-depth)
    - [domain](#domain)
    - [downsampling](#downsampling)
    - [field of view](#field-of-view)
    - [filtering](#filtering)
    - [group](#group)
    - [hierarchy](#hierarchy)
    - [interpolation](#interpolation)
    - [origin](#origin)
    - [physical](#physical)
    - [quantization](#quantization)
    - [resampling](#resampling)
    - [resolution](#resolution)


## Basic definitions

### array
An n-dimensional collection of discrete samples whose domain is a regular discrete (integer) grid.

Related terms: [sample](#sample), [image](#image), [hierarchy](#hierarchy)

### image
A static set of coherent visual information. For our purposes, ‘image’ and ‘digital image’ may be used interchangeably. 

Images can be represented in compact forms, for example as a compressed sequence of bytes or as a discrete function over a finite domain. For our purposes, the word ‘image’ by itself refers to raster images produced by displaying arrays and array-like data structures on a screen. Unless otherwise specified, this rastering occurs at regular equispaced intervals, the pixel pitch. 

An image is an abstract notion distinct from its representation, e.g. a discrete digital array. Colloquially, 'array' and 'image' are often used interchangeably. However, a rigorous technical definition separates the two, so that an image (a static set of coherent visual information) may be constituted by several arrays, for example.

Related terms: [array](#array), [sample](#sample), [pixel](#pixel), [voxel](#voxel), [axis](#axis), [dimension](#dimension)

### pixel
A single sample of a two-dimensional image.

Related terms: [sample](#sample), [voxel](#voxel)

### sample
A digital number representing a measurement of the energy sensed by a particular cell on a sensor at a discrete point in time. Because cells on a sensor correspond to elements of an array and pixels of an image, sample is often used interchangeably with pixel.

Related terms: [pixel](#pixel), [voxel](#voxel), [image](#image), [array](#array)

### voxel
A single sample of a three-dimensional image.

Related terms: [sample](#sample), [pixel](#pixel)

## Other definitions

### axis
The physical interpretation of a discrete, numeric, finite dimension. Generally represented with a 1D variable that is strictly monotonic and has the same name as the axis it represents. An axis must have physical units.

### bit-depth
The number of bits used in the quantization of a digital image that defines the number of unique values that can be represented by samples. For example, samples of images with a bit depth of ("8-bit images") can take up to 256 unique values.

Related terms: [quantization](#quantization)

### dimension
An independent extent of a domain. A domain has $N$ dimensions where $N$ is the minimum number of coordinates needed to identify any particular point within the domain. The length of a discrete, numeric, finite dimension establishes the number of indexable locations along that dimension.

### domain
A set of discrete locations in abstract space. A domain, or any location within a domain, may be described by multiple variables, but any given variable has only one domain. A domain has zero or more dimensions. The component dimensions of a domain need not be numeric, but when they are, the domain may be thought of as situated in a coordinate space. If a domain's dimensions are all axes, then that domain is situated in a physical space.

### downsampling
The act of resampling an image to a lower sample density (higher pixel spacing), often by an integer factor.
Sometimes this can require interpolation.

Related terms: [resampling](#resampling), [resolution](#resolution), [interpolation](#interpolation)

### field of view
The physical extent of the observed space. In microscopy, FOV may be expressed as the diameter of the circular view seen through the eyepiece. In scientific bioimaging, FOV is typically expressed as the horizontal, vertical, and/or diagonal extent of the space captured by the digital sensor. For example, the FOV for a 2D image may be $44mm$ by $22mm$, where $44mm$ is the width and $22mm$ is the height of the observed space.

### filtering
1. Usually referes to a convolution operation (a local, linear operation on the intensity values of an image).
2. Any operation that modifies the intensity values of an image.

### group
See [hierarchy](#hierarchy).

### hierarchy
A collection of nodes, connected in a tree-like structure.
A node can be either:
1. A group, i.e., a node that can have child nodes, and can contain metadata, but cannot contain array data.
2. An array. Array nodes cannot have child nodes.

Related terms: [group](#group), [array](#array)

### interpolation
A process that, given an image, produces new samples at points in the domain not on the discrete image grid.

The most common methods for interpolation are 'nearest-neighbor', 'bi-/tri-/n-linear', 'cubic', and 'windowed sinc'.

Related terms: [resampling](#resampling), [downsampling](#downsampling)

### origin
A special location that acts as a reference point, relative to which relative to which other locations are defined. Unless otherwise specified, the image's origin is the same as the array's origin (assuming the image is produced from an array). An array's origin is typically the point in the discrete domain with the minimum index (usually zero) for all dimensions. Physical or anatomical spaces can also have origins; for example, in MR imaging, the anterior/posterior commissure is commonly regarded as an origin for the brain.

The term 'offset' is sometimes used to refer to the origin.

### physical
Relating to quantities or measurements of the real world.

Examples:

* sample intensities measured by a physical sensor
    + photon count
    + [Hounsfield unit](https://en.wikipedia.org/wiki/Hounsfield_scale)
* distances / areas / volumes / times measured in images in physical units ($\mu m$, $mm$, seconds)
    + "the area of segment $A$ is $12 mm^2$"
    + "mitosis begins at time = $3.2 s$"

Non-examples:

* sample intensities not derived from sensors
    + segmentation id
    + the output of a deep neural network model
* distances / areas / volumes / times described by sample / array indexes
    + "the area of segment $B$ is $85$ pixels"
    + "mitosis begins at frame $51$"

### quantization
A process that converts a physical or continuous value to a digital representation with a particular precision. Samples of a quantized image can take one of a finite set of values defined by its bit depth.

Related terms: [bit-depth](#bit-depth)

### resampling
A process that generates a new array representing an image at a new resolution. 

The new resolution is often an integer multiple or fraction of the original image resolution, but need not be. Resampling methods often
consist of filtering and interpolation steps.

Related terms: [downsampling](#downsampling), [interpolation](#interpolation), [resolution](#resolution)

### resolution

The smallest difference in signal quantity that can be discriminated by a device or system. In the case of analog to digital signal conversion, resolution is determined by the number of bits used to represent the signal.

Colloquial uses of the term ‘resolution’ include the total number of samples in each dimension of an image (e.g., 640 by 420), and the set of spatial sampling intervals for an image (e.g. ‘spacing’, ‘pixel spacing’, or ‘pixel resolution’). For clarity, it may be prudent to avoid using the term ‘resolution’ to describe either the number of samples in an image or the spacing between samples.

Related terms: [bit-depth](#bit-depth), [resampling](#resampling)