# Janelia's Bioimaging File Formats
#### A handy list with links to their documentation.

---

#### bigcat:

[https://github.com/saalfeldlab/n5-ij/wiki/N5-Metadata-Dialects#bigcat](https://github.com/saalfeldlab/n5-ij/wiki/N5-Metadata-Dialects#bigcat)

---

#### Big Data Viewer: 

[The paper](https://www.nature.com/articles/nmeth.3392) \
The file format is described in the [supplementary information](https://static-content.springer.com/esm/art%3A10.1038%2Fnmeth.3392/MediaObjects/41592_2015_BFnmeth3392_MOESM239_ESM.pdf) \
[Online documentation](https://imagej.net/plugins/bdv/)

---

#### CellMap: 

[https://janelia-cellmap.github.io/cellmap-schemas/](https://janelia-cellmap.github.io/cellmap-schemas/) \
[https://janelia-cellmap.github.io/pydantic-zarr/](https://janelia-cellmap.github.io/pydantic-zarr/)

---

#### COSEM (predecessor to CellMap):

[https://github.com/janelia-cellmap/schemas](https://github.com/janelia-cellmap/schemas) \
[https://github.com/janelia-cellmap/schemas/blob/master/metadata.md#dataset-spatial-metadata](https://github.com/janelia-cellmap/schemas/blob/master/metadata.md#dataset-spatial-metadata) \
[https://github.com/saalfeldlab/n5-ij/wiki/N5-Metadata-Dialects#cosem](https://github.com/saalfeldlab/n5-ij/wiki/N5-Metadata-Dialects#cosem)

---

#### DAT (FIB-SEM):

The FIB-SEM .dat format is a completely custom file format for the Focused Ion Beam Scanning Electron Microscope system developed at Janelia. Documentation can be found in two repositories:

[https://github.com/janelia-cellmap/fibsem-tools/](https://github.com/janelia-cellmap/fibsem-tools/) \
[https://github.com/clbarnes/jeiss-specs](https://github.com/clbarnes/jeiss-specs)

---

#### H5J:

[https://data.janelia.org/h5j](https://data.janelia.org/h5j)

---

#### n5-viewer:

links:

[https://github.com/saalfeldlab/n5-viewer](https://github.com/saalfeldlab/n5-viewer) \
[https://github.com/saalfeldlab/n5-ij/wiki/N5-Metadata-Dialects#n5-viewer](https://github.com/saalfeldlab/n5-ij/wiki/N5-Metadata-Dialects#n5-viewer)


Supported metadata:

##### multichannel

Channels MUST be stored in separate groups, that MUST be named `c0`, `c1`, etc
Single-channel images must be stored under a group named `c0`

#####  multiscale

Multiscale images MUST be stored in separate groups and MUST be children of a channel group (`c[i]`, see above).
The group for each scale level MUST be name `s0`, `s1`, ... `s[N]`.


#####  spatial resolution

Spatial resolution MUST be stored as metadata in the multiscale groups (`s[i]`, see above).

As one of the

```
"pixelResolution": {
   "unit": "um",
   "dimensions": [ <rx>, <ry>, <rz> ]
}
```

```
"pixelResolution": [ <rx>, <ry>, <rz> ]
```

where `rx`, `ry`, and `rz` are the resolutions of x, y, and z, respectively

TODO: document `"downsamplingFactors"`

#####  example

TODO finish this
```
c0 
    s0
    s1
    s2
c1 
    s0
    s1
    s2
```


---

#### OME-Zarr:

OME-NGFF, a.k.a. OME-Zarr, is not a Janelia file format, but is widely used at Janelia.

[https://ngff.openmicroscopy.org/0.4/](https://ngff.openmicroscopy.org/0.4/)
